### ISSUE TITLE
onAttachmentAdd doesn't affect onChange update.

### ISSUE THREAD

**Issue by ranggabadrus** [abhaynikam/react-trix-rte#18]
i got image value from onAttachmentAdd but i can't see it on onChange. then how i can combine image and text as output?
<img width="195" alt="Screenshot 2020-09-25 at 5 14 20 PM" src="https://user-images.githubusercontent.com/46615811/94249560-a6428580-ff52-11ea-9b32-9b05f686e660.png">

**Comment by abhaynikam** [comment]
Thanks for raising the issue. From what I understand you want the attachment to be accessible in the onChange handler. The `onChange` event is only fired when changes are made to the editor and in order to access the attachment, you can store the attachment in the React state and access it in the onChange handler. 

AFAIK trix editor won't provide the attachment in the onChange event. 

On second thought, I see you are trying to do file upload in trix attachment. Trix editor works well with Rails Action Text(as it was built by Basecamp), in those events setting `isRailsDirectUpload` might be helpful for direct upload.

Hope that helps :)

**Comment by tilvan** [comment]
@abhaynikam Hi! I'm trying to use `isRailsDirectUpload` with `railsDirectUploadUrl` or/and `railsBlobUrl` or without them.
Result is one - it's not working. File doesn't sent to backend.

```
import 'trix/dist/trix';
import { ReactTrixRTEInput, ReactTrixRTEToolbar } from 'react-trix-rte';

<Fragment>
      <ReactTrixRTEToolbar toolbarId={`react-trix-rte-editor-${name}`} />
      <ReactTrixRTEInput
        name={name}
        toolbarId={`react-trix-rte-editor-${name}`}
        defaultValue={value}
        className={styles.editor}
        isRailsDirectUpload={true}
        railsDirectUploadUrl={`${HOST}/rails/active_storage/direct_uploads'`}
        railsBlobUrl={`${HOST}/rails/active_storage/blobs/:signed_id/:filename`}
      />
</Fragment>      
```
